apiVersion: v1
kind: Service
metadata:
  name: personalization-flink-dashboard
  namespace: personalization-blue
spec:
  type: NodePort
  selector:
    app: personalization
    component: jobmanager
  ports:
    - name: flink-dashboard
      port: 8081
      targetPort: 8081
      nodePort: 30011
