state.backend.type: rocksdb
execution.checkpointing.interval: 10s
execution.checkpointing.mode: EXACTLY_ONCE
execution.checkpointing.incremental: true
execution.checkpointing.num-retained: 3
execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
execution.checkpointing.dir: s3://checkpoints/phase-3
pipeline.generic-types: false

s3.endpoint: http://localhost:30014
s3.path.style.access: true

taskmanager.memory.process.size: 2gb
taskmanager.memory.network.min: 256mb
taskmanager.memory.network.max: 256mb
