apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-job-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sunyanl1236/k8s-personalization
    targetRevision: HEAD
    path: manifests/flink/green
  destination:
    server: https://kubernetes.default.svc
    namespace: personalization-green
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
